Cleaning up the Jenkins test driver to be more robust to path issues (and to help with using it outside of Jenkins).

diff --git a/admin/jenkins_cxxtest b/admin/jenkins_cxxtest
--- a/admin/jenkins_cxxtest
+++ b/admin/jenkins_cxxtest
@@ -1,6 +1,11 @@
 #!/bin/bash
 
-export PATH=$WORKSPACE/vpython/bin:$PATH
+if test -z "$WORKSPACE"; then
+    echo "ERROR: \$WORKSPACE not defined"
+    exit 1
+fi
+
+export PATH="$WORKSPACE/vpython/bin:$PATH"
 g++ --version
 
 # Setup virtual Python environment
@@ -13,29 +18,28 @@ vpython/bin/easy_install ply
 vpython/bin/easy_install ordereddict
 vpython/bin/easy_install gcovr
 vpython/bin/easy_install pyutilib.th
-cd cxxtest/python
-../../vpython/bin/python setup.py install
+cd "$WORKSPACE"/cxxtest/python
+"$WORKSPACE"/vpython/bin/python setup.py install
 
 # Cleanup test directory
-cd ../test
+cd "$WORKSPACE"/cxxtest/test
 make clean
-cd ../..
+cd "$WORKSPACE"
 
 # Run tests
 export CXXTEST_GCOV_FLAGS='-fprofile-arcs -ftest-coverage'
-vpython/bin/nosetests -v -v --with-xunit --xunit-file=$WORKSPACE/TEST-cxxtest.xml -w $WORKSPACE/cxxtest/test
+vpython/bin/nosetests -v -v -w "$WORKSPACE"/cxxtest/test \
+    --with-xunit --xunit-file="$WORKSPACE"/TEST-cxxtest.xml 
 
 # Generate code coverage
-cd cxxtest
-../vpython/bin/gcovr -v -r $WORKSPACE/cxxtest -x -o $WORKSPACE/cxxtest/test/coverage.xml --gcov-filter '.*#test#(\.\.|\^)#cxxtest#.*gcov'
+cd "$WORKSPACE"/cxxtest
+"$WORKSPACE"/vpython/bin/gcovr -v -d -r "$WORKSPACE"/cxxtest \
+    -x -o "$WORKSPACE"/cxxtest/test/coverage.xml \
+    --gcov-filter '.*#test#(\.\.|\^)#cxxtest#.*gcov'
 
 echo "DONE"
 
-# Cleanup old gcov files
-cd $WORKSPACE
-\rm -f *.gcov cxxtest/*.gcov doc/*.gcov doc/examples/*.gcov
-\rm -f *.gcno cxxtest/*.gcno doc/*.gcno doc/examples/*.gcno
-\rm -f *.gcda cxxtest/*.gcda doc/*.gcda doc/examples/*.gcda
+# Cleanup old test files
 cd $WORKSPACE/cxxtest/test
 make clean
 
